config/routes.rb
News::Engine.routes.draw do
  root to: 'stories#index'
  get 'seed'=>'stories#seed'
  get 'submit'=>'stories#new'
  get 'new' => 'stories#new'

  resources :stories
  resources :comments, only: [:new, :create]

  resources :votes, only: [:create] do
    get '/'=>'votes#create'
  end
end

app/models/news/comment.rb
module News
  class Comment < ActiveRecord::Base
    acts_as_nested_set
    alias_method :replies, :children

    before_validation :set_story_id
    def set_story_id
      self.story_id = parent.story_id if child?
    end

    belongs_to :story
    validates :body, :story, presence: true

    # Direction will be either up or down
    def vote!(direction)
      change = case direction.to_sym
      when :up then 1
      when :down then -1
      else raise "Unexpected vote direciton, must be up or down."
      end

      update_attribute(:points, points + change)
    end
  end
end

app/models/news/news.rb
module News
  module News
    def self.table_name_prefix
      'news_news_'
    end
  end
end

app/models/news/story.rb
# == Schema Information
#
# Table name: news_stories
#
#  id         :integer          not null, primary key
#  title      :string
#  url        :string
#  image      :string
#  points     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'uri'

module News
  class Story < ActiveRecord::Base
    has_many :comments

    validates :url, :title, presence: true
    validate :validate_url
    def validate_url
      # Add HTTP if it's needed
      url.gsub!(/\Awww\./, 'http://www.')
      valid = begin
         uri = URI.parse(url)
         uri.kind_of?(URI::HTTP)
      rescue URI::InvalidURIError
        false
      end
      errors.add :url, 'is not a valid URL' unless valid
    end

    extend FriendlyId
    friendly_id :title, use: [:slugged]


    def vote!(direction)
      change = case direction.to_sym
      when :up then 1
      when :down then -1
      else "Unexpected vote direciton, must be up or down."
      end

      update_attribute(:points, points + change)
    end
  end
end

app/controllers/news/application_controller.rb
module News
  class ApplicationController < ActionController::Base
  end
end

app/controllers/news/comments_controller.rb
module News
  class CommentsController < ApplicationController
    def new
      @comment = build_new_comment
    end

    def create
      @comment = Comment.new(comment_params)
      if @comment.save
        redirect_to @comment.story
      else
        render 'new'
      end
    end

    private
    def build_new_comment
      if params[:reply_to]
        parent = Comment.find(params[:reply_to])
        return parent.replies.build
      elsif params[:story_id]
        @story = Story.find(params[:story_id])
        return @story.comments.build
      else
        raise "Must provide either a story_id or a reply_to"
      end
    end

    def comment_params
      params.require(:comment).permit(:body, :story_id, :parent_id)
    end
  end
end

app/controllers/news/stories_controller.rb
require 'faker'

module News
  class StoriesController < ApplicationController
    def index
      @stories = Story.order('points DESC').all
    end

    def show
      @story = Story.friendly.find(params[:id])
    end

    def new
      @story = Story.new
    end

    def create
      @story = Story.new(story_params)
      @story.approved = false
      if @story.save
        redirect_to root_path, success: "Thanks for your submission - we'll check it and put it on the site ASAP"
      else
        render 'new'
      end
    end


    # Creates a few random stories to get us going
    def seed
      Story.delete_all
      Comment.delete_all
      20.times do |n|
        story = Story.create!(
          title: Faker::Lorem.sentence,
          url: Faker::Internet.url,
          points: rand(-100..100),
          image: Faker::Avatar.image,
          created_at: Faker::Time.backward(14),
        )

        rand(0..10).times do |x|
          comment = story.comments.create!(
            body: Faker::Lorem.paragraph(2),
            points: rand(-100..100),
          )

          rand(0..3).times do |y|
            comment.replies.create!(
              body: Faker::Lorem.paragraph(rand(1..9)),
              points: rand(-10..10)
            )
          end
        end
      end
      redirect_to root_path
    end

    private
      def story_params
        params.require(:story).permit(:url, :title, :submitter_name, :submitter_email)
      end
  end
end

app/controllers/news/votes_controller.rb
module News
  class VotesController < ApplicationController
    def create
      if params[:comment_id]
        @object = Comment.find(params[:comment_id])
      elsif params[:story_id]
        @object = Story.find(params[:story_id])
      end
      @object.vote! params[:direction]
      respond_to do |format|
        format.html { redirect_to(@object.try(:story) || @object) }
        format.json { render json: { points: @object.points } }
      end
    end
  end
end

app/helpers/news/application_helper.rb
module News
  module ApplicationHelper
    def error_messages_for(obj)
      return unless obj.errors.any?
      render 'news/shared/errors_summary', errors: obj.errors.full_messages
    end

    # Creates an ajax link for voting
    # Takes the object we are voting on
    # and the direction we're voting
    def vote_link_for(obj, direction)
      puts obj.class.inspect
      attr = case obj.class.name
      when 'News::Story' then { story_id: obj.id }
      when 'News::Comment' then { comment_id: obj.id }
      else raise "Unknown vote subject: #{obj.class}"
      end

      attr.merge!(direction: direction)
      link_to '', votes_path(attr), class: "glyphicon glyphicon-chevron-#{direction} story-item-vote-arrow js-vote"
    end
  end
end

app/views/layouts/news/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:300%7CRoboto:700,400" rel="stylesheet" type="text/css">
	<meta charset="ucf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<title>How a Car Works - News</title>
  	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  	<%= stylesheet_link_tag    "news/application", media: "all" %>
  	<%= javascript_include_tag "news/application" %>
  	<%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/news/comments/_comment.html.erb
<div class="comment-item">
  <div class="comment-item-voting">
    <%= link_to '', votes_path(comment_id: comment.id, direction: :up), class: "glyphicon glyphicon-chevron-up story-box-vote-arrow" %>
    <%= link_to '', votes_path(comment_id: comment.id, direction: :down), class: "glyphicon glyphicon-chevron-down story-box-vote-arrow" %>
  </div><!-- comment-item-voting-->
  <div class="comment-item-details">
    <div class="comment-item-meta">
      <%= comment.points %> points
      <%= time_ago_in_words(comment.created_at) %> ago
    </div>
    <%= simple_format comment.body %>

    <%= link_to 'Reply', new_comment_path(reply_to: comment.id) %>
  </div><!-- comment-item-meta -->

  <div class="comment-replies">
    <% comment.replies.each do |reply| %>
      <%= render 'news/comments/comment', comment: reply %>
    <% end %>
  </div>
</div><!--comment-item-->

app/views/news/comments/new.html.erb
<h1>Add a comment</h1>

<%= form_for @comment do |f| %>
  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :story_id %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/news/shared/_errors_summary.html.erb
<div class="errors-summary">
  <p>There are errors with the form that you need to fix:</p>
  <ul>
    <% errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
</div>

app/views/news/stories/index.html.erb
<div class="stories-list">
  <div class="stories-actions" style="margin-bottom: 20px; text-align: center">
    <%= link_to 'Submit a story', new_story_path, class: 'btn btn-primary' %>
  </div>

  <% @stories.each do |story| %>
    <div class="story-item">
      <div class="story-item-voting">
        <%= vote_link_for story, :up %>
        <%= story.points %>
        <%= vote_link_for story, :down %>
      </div><!-- .story-item-vote -->

      <div class="story-item-details">
        <a href="<%= story_path(story) %>">
          <img class="story-item-image" src="<%= story.image %>"/>
        </a>
        <h3><%= link_to story.title, story %></h3>

        <%= link_to pluralize(story.comments.count, 'comment'), story_path(story, anchor: 'comments'), class: "story-item-details-comment-count" %>.
        Submitted <%= time_ago_in_words(story.created_at) %> ago
      </div><!-- .story-item-details -->
    </div><!-- .story-item -->
  <% end %>
</div><!-- stories-list -->

app/views/news/stories/new.html.erb
<div class="container">
  <h1>Submit a story</h1>

  <p>Found something of interest to our community of 200,000 car enthusiasts?  Tell us and we'll
    share it with everyone.</p>
  <%= form_for @story do |f| %>
    <%= error_messages_for @story %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :url, "URL of story" %>
      <%= f.text_field :url, class: 'form-control' %>
    </div>

    <fieldset>
      <legend>About you</legend>
      <div class="form-group">
        <%= f.label :submitter_name, 'Your name' %>
        <%= f.text_field :submitter_name, class: 'form-control' %>
        <p class="help-block">We'll credit you with finding this story. Feel
          free to leave it blank.</p>
      </div>

      <div class="form-group">
        <%= f.label :submitter_email, 'Your email' %>
        <%= f.text_field :submitter_email, class: 'form-control' %>
        <p class="help-block">Optional - We'll email you when your link is live</p>
      </div>
    </fieldset>

    <%= f.submit 'Submit story', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/news/stories/show.html.erb
<div class="container">
  <div class="story-header">
    <%= image_tag @story.image, alt: @story.title %>

    <%= vote_link_for @story, :up %>

    <h1><%= link_to @story.title, @story.url %></h1>

    <div class="story-voting">
      <span class="label label-info label-story-points"><%= @story.points %> points</span>
    </div>

    <div class="story-meta">
      Story submitted <%= time_ago_in_words @story.created_at %> ago.
      <h3 id="comments"><%= pluralize(@story.comments.count, 'comment') %></h3>
    </div><!-- .story-meta -->
  </div><!-- story-header -->

  <%= form_for @story.comments.build, html:{ class: 'story-comment-form'} do |f| %>
    <%= f.hidden_field :story_id %>
    <%= f.text_area :body, placeholder: "Comment on this story.", id: 'story_comment_body' %>

    <%= f.submit 'Add comment', class: 'btn btn-add-comment', id: "story_comment_submit" %>
  <% end %>

  <div class="comments-list">
    <% @story.comments.roots.order('points DESC').each do |comment| %>
    <%= render comment %>
    <% end %>
  </div> <!-- .comments-list -->
</div>